### ISSUE TITLE
Updates database components and populates with SampleData

### ISSUE THREAD

**Issue by isaakwheeler** [MobileApps-Cascadia/campus-guidebook-android#67]
Update app to follow common architecture patterns and dependency injection. Repository and models updated. Correct error preventing named time zone usage, resulting in errant Daylight Saving Time behavior. Add sample data for proof of concept.

DOD: Database initialized with sample data for all entities, model(s) demonstrate correct functionality under Daylight Saving Time, sample data is inserted cleanly upon each execution.

**Comment by gomezfox** [comment]
* The SampleData class now has a method to clear the database and add all the data.  It is called from AppDatabase after the builder runs. The callback is left in for now, but it only logs that it was called.
* That named timezone I had to change to -08:00 on the zoom call is now back to Cascadia's local timezone "America/Los_Angeles" and is using ZonedDateTime.
* Because of that change, Daylight Saving Time is now handled completely automatically. To see this, look at the database, where one sample event is March 1 (PST) and the other in October (PDT).
* A description field is added to Sustainability, since that is needed to implement the details page.
